### ISSUE TITLE
Clock file issue with chronos  / pc069 / enclustra-a35 with tag test/full-chain/b1

### ISSUE THREAD

**Issue by DavidCussans** [DUNE-DAQ/timing-board-software#99]
`io reset` fails for chronos  / pc069 / enclustra-a35 with tag test/full-chain/b1

```
RuntimeError:  Clock config file not found for key: pc069_5344_chronos_input_1
```

Output from dtsbutler :

```
dtsbutler -c connections.xml io EPT2 reset  2>&1 | tee ~/Download/chronos_pc069a_enclustra
_ept2_240215_02.log
Created device EPT2
Design 'chronos' on board 'pc069' on carrier 'enclustra-a35' with frequency 62.5 MHz
Resetting EPT2
ERROR ('RuntimeError' exception): ' Clock config file not found for key: pc069_5344_chronos_input_1'

File "/home/phdgc/DUNE/dunedaq/fddaq-v4.2.0/install/timing/lib64/python/timing/cli/io.py", line 121, in reset
   lIO.reset(lClockSource)
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/phdgc/DUNE/dunedaq/fddaq-v4.2.0/install/timing/bin/dtsbutler", line 99, in <module>
    cli(obj=DTSContext())
  File "/cvmfs/dunedaq.opensciencegrid.org/spack/releases/fddaq-v4.2.1-c8/.venv/lib/python3.10/site-packages/click/core.py",
line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/cvmfs/dunedaq.opensciencegrid.org/spack/releases/fddaq-v4.2.1-c8/.venv/lib/python3.10/site-packages/click/core.py",
line 1055, in main
    rv = self.invoke(ctx)
  File "/cvmfs/dunedaq.opensciencegrid.org/spack/releases/fddaq-v4.2.1-c8/.venv/lib/python3.10/site-packages/click/core.py",
line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/cvmfs/dunedaq.opensciencegrid.org/spack/releases/fddaq-v4.2.1-c8/.venv/lib/python3.10/site-packages/click/core.py",
line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/cvmfs/dunedaq.opensciencegrid.org/spack/releases/fddaq-v4.2.1-c8/.venv/lib/python3.10/site-packages/click/core.py",
line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/cvmfs/dunedaq.opensciencegrid.org/spack/releases/fddaq-v4.2.1-c8/.venv/lib/python3.10/site-packages/click/core.py",
line 760, in invoke
    return __callback(*args, **kwargs)
  File "/cvmfs/dunedaq.opensciencegrid.org/spack/releases/fddaq-v4.2.1-c8/.venv/lib/python3.10/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/cvmfs/dunedaq.opensciencegrid.org/spack/releases/fddaq-v4.2.1-c8/.venv/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/phdgc/DUNE/dunedaq/fddaq-v4.2.0/install/timing/lib64/python/timing/cli/io.py", line 121, in reset
    lIO.reset(lClockSource)
RuntimeError:  Clock config file not found for key: pc069_5344_chronos_input_1

```

**Comment by strilov** [comment]
Issue appears to be a hardware/firmware mis-match, no pc069 boards have a si5344 PLL
